#!/usr/bin/python
# sax_via_sliding_ window on hr_1

import numpy as np
from saxpy.sax import sax_via_window

#Read each line in 'hr_1.txt' and save heart rate column in 'dat' array
hr_1 = open('hr_1.txt', 'r')
line = hr_1.readline()
dat = np.array([])
while line:
        hr_value = line.split()
        dat = np.append(dat, int(hr_value[-1]))
        line = hr_1.readline()
sax_none = sax_via_window(dat, win_size=6, paa_size=3, alphabet_size=3, nr_strategy=None, z_threshold=0.01)
#print(sax_none)

# Get size of each sax word
word_freq = {}
for key, val in sax_none.items():
  word_freq[key] = len(val)
print(word_freq)


hr_1.close()
